PARAMETER ...
Namespace(batch_size=5, decay_rate=0.0001, epoch=200, gpu='0', learning_rate=0.001, log_dir='deform_contactnet', model='deform_contactnet', num_category=1, num_point=1024, optimizer='Adam', process_data=False, use_cpu=False, use_normals=True, use_uniform_sample=False)
Load dataset ...
23
No existing model, starting training from scratch...
Epoch 1 (1/200):
  0%|                                                                                              | 0/3 [00:00<?, ?it/s]
5 8 8894
target:  tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')
pred:  tensor([[0.5978, 0.5978, 0.5978,  ..., 0.6095, 0.6087, 0.6047],
        [0.5979, 0.5979, 0.6045,  ..., 0.5975, 0.5979, 0.5979],
        [0.6983, 0.5566, 0.5498,  ..., 0.5103, 0.5137, 0.6983],
        [0.6589, 0.6944, 0.6514,  ..., 0.6965, 0.6589, 0.6709],
        [0.5098, 0.5554, 0.5699,  ..., 0.5040, 0.5142, 0.5281]],
       device='cuda:0', grad_fn=<ViewBackward>)
  0%|                                                                                              | 0/3 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 259, in <module>
    main(args)
  File "train.py", line 206, in main
    num_correct += (predictions == target).sum()
UnboundLocalError: local variable 'num_correct' referenced before assignment